// <auto-generated />
using System;
using BibliotecaVideojuegosApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BibliotecaVideojuegosApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("BibliotecaVideojuegosApi.Models.CopiaVideoJuego", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EstadoPrestado")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VideoJuegoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("CopiaVideoJuego");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EstadoPrestado = false,
                            VideoJuegoId = 1
                        },
                        new
                        {
                            Id = 2,
                            EstadoPrestado = false,
                            VideoJuegoId = 2
                        },
                        new
                        {
                            Id = 3,
                            EstadoPrestado = false,
                            VideoJuegoId = 3
                        },
                        new
                        {
                            Id = 4,
                            EstadoPrestado = false,
                            VideoJuegoId = 4
                        },
                        new
                        {
                            Id = 5,
                            EstadoPrestado = false,
                            VideoJuegoId = 5
                        },
                        new
                        {
                            Id = 6,
                            EstadoPrestado = false,
                            VideoJuegoId = 6
                        },
                        new
                        {
                            Id = 7,
                            EstadoPrestado = false,
                            VideoJuegoId = 7
                        },
                        new
                        {
                            Id = 8,
                            EstadoPrestado = false,
                            VideoJuegoId = 8
                        },
                        new
                        {
                            Id = 9,
                            EstadoPrestado = false,
                            VideoJuegoId = 9
                        },
                        new
                        {
                            Id = 10,
                            EstadoPrestado = false,
                            VideoJuegoId = 10
                        },
                        new
                        {
                            Id = 11,
                            EstadoPrestado = false,
                            VideoJuegoId = 11
                        },
                        new
                        {
                            Id = 12,
                            EstadoPrestado = false,
                            VideoJuegoId = 12
                        },
                        new
                        {
                            Id = 13,
                            EstadoPrestado = false,
                            VideoJuegoId = 13
                        },
                        new
                        {
                            Id = 14,
                            EstadoPrestado = false,
                            VideoJuegoId = 14
                        },
                        new
                        {
                            Id = 15,
                            EstadoPrestado = false,
                            VideoJuegoId = 15
                        },
                        new
                        {
                            Id = 16,
                            EstadoPrestado = false,
                            VideoJuegoId = 16
                        },
                        new
                        {
                            Id = 17,
                            EstadoPrestado = false,
                            VideoJuegoId = 17
                        },
                        new
                        {
                            Id = 18,
                            EstadoPrestado = false,
                            VideoJuegoId = 18
                        },
                        new
                        {
                            Id = 19,
                            EstadoPrestado = false,
                            VideoJuegoId = 19
                        },
                        new
                        {
                            Id = 20,
                            EstadoPrestado = false,
                            VideoJuegoId = 20
                        },
                        new
                        {
                            Id = 21,
                            EstadoPrestado = false,
                            VideoJuegoId = 21
                        },
                        new
                        {
                            Id = 22,
                            EstadoPrestado = false,
                            VideoJuegoId = 22
                        },
                        new
                        {
                            Id = 23,
                            EstadoPrestado = false,
                            VideoJuegoId = 23
                        });
                });

            modelBuilder.Entity("BibliotecaVideojuegosApi.Models.PrestamoJuego", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CopiaVideoJuegoId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("FechaDevolucion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaPrestamo")
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PrestamoVideoJuego");
                });

            modelBuilder.Entity("BibliotecaVideojuegosApi.Models.VideoJuego", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Plataforma")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("VideoJuego");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Genero = "Aventura",
                            Plataforma = "Switch",
                            Titulo = "The Legend of Zelda: Breath of the Wild"
                        },
                        new
                        {
                            Id = 2,
                            Genero = "Accion",
                            Plataforma = "PS4",
                            Titulo = "God of War"
                        },
                        new
                        {
                            Id = 3,
                            Genero = "Accion",
                            Plataforma = "PC",
                            Titulo = "God of War"
                        },
                        new
                        {
                            Id = 4,
                            Genero = "RPG",
                            Plataforma = "PC",
                            Titulo = "The Witcher 3: Wild Hunt"
                        },
                        new
                        {
                            Id = 5,
                            Genero = "RPG",
                            Plataforma = "PS4",
                            Titulo = "The Witcher 3: Wild Hunt"
                        },
                        new
                        {
                            Id = 6,
                            Genero = "Aventura",
                            Plataforma = "PS4",
                            Titulo = "Red Dead Redemption 2"
                        },
                        new
                        {
                            Id = 7,
                            Genero = "Aventura",
                            Plataforma = "PC",
                            Titulo = "Red Dead Redemption 2"
                        },
                        new
                        {
                            Id = 8,
                            Genero = "Sandbox",
                            Plataforma = "PC",
                            Titulo = "Minecraft"
                        },
                        new
                        {
                            Id = 9,
                            Genero = "Sandbox",
                            Plataforma = "Switch",
                            Titulo = "Minecraft"
                        },
                        new
                        {
                            Id = 10,
                            Genero = "Plataformas",
                            Plataforma = "Switch",
                            Titulo = "Super Mario Odyssey"
                        },
                        new
                        {
                            Id = 11,
                            Genero = "RPG",
                            Plataforma = "PS5",
                            Titulo = "Elden Ring"
                        },
                        new
                        {
                            Id = 12,
                            Genero = "RPG",
                            Plataforma = "PC",
                            Titulo = "Elden Ring"
                        },
                        new
                        {
                            Id = 13,
                            Genero = "Deportes",
                            Plataforma = "PS5",
                            Titulo = "FIFA 23"
                        },
                        new
                        {
                            Id = 14,
                            Genero = "Deportes",
                            Plataforma = "PC",
                            Titulo = "FIFA 23"
                        },
                        new
                        {
                            Id = 15,
                            Genero = "Simulacion",
                            Plataforma = "Switch",
                            Titulo = "Animal Crossing: New Horizons"
                        },
                        new
                        {
                            Id = 16,
                            Genero = "RPG",
                            Plataforma = "PC",
                            Titulo = "Cyberpunk 2077"
                        },
                        new
                        {
                            Id = 17,
                            Genero = "Carreras",
                            Plataforma = "Switch",
                            Titulo = "Mario Kart 8"
                        },
                        new
                        {
                            Id = 18,
                            Genero = "Metroidvania",
                            Plataforma = "Switch",
                            Titulo = "Hollow Knight"
                        },
                        new
                        {
                            Id = 19,
                            Genero = "Metroidvania",
                            Plataforma = "PC",
                            Titulo = "Hollow Knight"
                        },
                        new
                        {
                            Id = 20,
                            Genero = "RPG",
                            Plataforma = "PC",
                            Titulo = "Dark Souls III"
                        },
                        new
                        {
                            Id = 21,
                            Genero = "Roguelike",
                            Plataforma = "Switch",
                            Titulo = "Hades"
                        },
                        new
                        {
                            Id = 22,
                            Genero = "RPG",
                            Plataforma = "PS4",
                            Titulo = "Persona 5"
                        },
                        new
                        {
                            Id = 23,
                            Genero = "Accion",
                            Plataforma = "PS4",
                            Titulo = "Grand Theft Auto V"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
